.Dd June 8, 2024
.Dt KBD 4
.Os
.Sh NAME
.Nm kbd
.Nd Xorg keyboard input driver
.Sh SYNOPSIS
.Bd -literal
Section "InputDevice"
  Identifier "idevname"
  Driver "kbd"
  ...
EndSection
.Ed
.Sh DESCRIPTION
.Nm
is an
.Xr Xorg 1
server input driver for keyboards.
The driver provides a keyboard input device supporting the standard
OS-provided keyboard interface on BSD, Hurd, illumos, and Solaris.
.Ss CONFIGURATION
The
.Xr Xorg 1
server automatically configures itself if no configuration is set.
If desired, input device options may be set in either a
.Xr xorg.conf 5
file, or an
.Pa xorg.conf.d
snippet.
.Pp
Please refer to
.Xr xorg.conf 5
for general configuration details and for
options that can be used with all input drivers.
This section only covers configuration details specific to this driver.
.Pp
The following driver options are supported:
.Bl -tag -width indent
.It Ic Option Do Cm Device Dc Do Ar string Dc
Specify the keyboard device.
Default: the OS's default console keyboard input source.
Property:
.Dq Device Node
.Pq read-only .
.It Ic Option Do Cm Protocol Dc Do Ar string Dc
Specify the keyboard protocol.
Valid protocol types include:
.Pp
.Dv Standard , Dv Xqueue .
.Pp
Not all protocols are supported on all platforms.
Default:
.Dq Dv Standard .
.It Ic Option Do Cm XLeds Dc Do Ar ledlist Dc
Make the keyboard LEDs specified in ledlist available for client use
instead of their traditional functions
.Pq Scroll Lock, Caps Lock, and Num Lock .
The numbers in this list are in the range of 1 to 3.
Default: empty list.
.It Ic Option Do Cm XkbRules Dc Do Ar rules Dc
Specify which XKB rules file to use for interpreting the
.Cm XkbModel , Cm XkbLayout , Cm XkbVariant , No and Cm XkbOptions
settings.
Default:
.Dq Dv base
for most platforms.
If you use the
.Dq Dv base
value then you can find listing of all valid values
for these four options in the
.Pa __xkb_path__/rules/base.lst
file.
.It Ic Option Do Cm XkbModel Dc Do Ar modelname Dc
Specify the XKB keyboard model name.
Default:
.Dq Dv pc105
for most platforms.
.It Ic Option Do Cm XkbLayout Dc Do Ar Layoutname Dc
Specify the XKB kayboard layout name.
This is usually the country or language type of the keyboard.
Default:
.Dq Dv us
for most platforms.
.It Ic Option Do Cm XkbOptions Dc Do Ar options Dc
Specify the XKB keyboard option componenets.
These can be used to enhance the keyboard behavior.
Default: not set.
.El
.Pp
For a list of available xkb options, see
.Xr xkeyboard-config 7 .
.Sh EXAMPLES
The following
.Xr xorg.conf 5
fragment ensures that user will be able to switch between
.Dv us
and
.Dv sk
layouts by pressing the
.Dq menu
key.
The Scroll Lock LED shows which layout is currently active.
.Pp
The
.Cm XkbVariant
option defines which variants of the two layouts should be used.
In case of the us layout its default variant is used.
In case of the sk layout its qwerty variant is used.
.Bd -literal
    Section "InputDevice"
        Identifier   "Generic Keyboard"
        Driver       "kbd"
        Option       "CoreKeyboard"
        Option       "XkbRules"      "base"
        Option       "XkbModel"      "pc105"
        Option       "XkbLayout"     "us,sk"
        Option       "XkbVariant"    ",qwerty"
        Option       "XkbOptions"    "grp:menu_toggle,grp_led:scroll"
      EndSection
.Ed
.Sh SEE ALSO
.Xr setxkbmap 1 ,
.Xr Xorg 1 ,
.Xr xorg.conf 5 ,
.Xr X 7 ,
.Xr xkeyboard-config 7
.Sh HISTORY
The
.Nm
driver is a replacement for the built-in
.Sy keyboard
driver formerly included in the
.Sy XFree86
server.
